import React, { createContext, useCallback, useContext, useEffect, useState } from 'react';
import api, { API_BASE_URL } from '../services/api';
import { AuthContext } from './AuthContext';

export const DetectionContext = createContext();
const fallbackDatasets = [{
    id: '0',
    name: 'EVT-CLIP Inspection Profile',
    description: 'Active EVT-CLIP product model profile.',
    categories: ['bottle', 'cable', 'capsule', 'metal_nut', 'pill'],
    imagesCount: 0,
    category: 'Production',
    created: 'Built-in',
}];

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

const mapDetection = (item) => ({
    id: item.id,
    datasetId: String(item.dataset_name || '0'),
    datasetName: item.dataset_name || 'EVT-CLIP Inspection Profile',
    category: item.category || 'unknown',
    predictedCategory: item.predicted_category || null,
    anomalyScore: Number(item.anomaly_score || 0),
    prediction: item.prediction,
    confidence: Number(item.confidence || 0),
    inferenceTime: Math.round(Number(item.inference_time || 0) * 1000),
    inferenceSeconds: Number(item.inference_time || 0),
    timestamp: item.created_at?.replace('T', ' ').slice(0, 19) || '',
    imageName: item.original_image_path?.split('/').pop() || 'uploaded-image',
    originalImage: '',
    preprocessedImage: '',
    efficientadHeatmapImage: '',
    patchcoreHeatmapImage: '',
    stage2HeatmapImage: '',
    stage3HeatmapImage: '',
    classicalCvHeatmapImage: '',
    yoloRoiMaskImage: '',
    hybridHeatmapImage: '',
    bboxOverlayImage: '',
    heatmapImage: '',
    maskImage: '',
    overlayImage: '',
    notes: [item.category_validation_message, item.image_quality_message].filter(Boolean).join(' ') || 'Generated by the verified EVT-CLIP backend.',
    threshold: item.threshold,
    resultValid: item.result_valid !== false,
    reviewRequired: Boolean(item.review_required),
    reviewReason: item.review_reason || null,
    rejectionCode: item.rejection_code || null,
    categoryValidator: item.category_validator || null,
    workerCache: item.worker_cache || null,
    validationSeconds: Number(item.validation_seconds || 0),
    efficientadSeconds: Number(item.efficientad_seconds || 0),
    patchcoreSeconds: Number(item.patchcore_seconds || 0),
    refinerSeconds: Number(item.refiner_seconds || 0),
    imageQualityState: item.image_quality_state || null,
    imageQualityMessage: item.image_quality_message || null,
    decisionSource: item.decision_source || null,
    route: item.route || null,
    localizationSource: item.localization_source || null,
    primarySpecialist: item.primary_specialist || null,
    efficientadImageScore: item.efficientad_image_score == null ? null : Number(item.efficientad_image_score),
    patchcoreImageScore: item.patchcore_image_score == null ? null : Number(item.patchcore_image_score),
    stage2MapScore: item.stage2_map_score == null ? null : Number(item.stage2_map_score),
    stage3MapScore: item.stage3_map_score == null ? null : Number(item.stage3_map_score),
    classicalCvScore: item.classical_cv_score == null ? null : Number(item.classical_cv_score),
    classicalCvSeconds: Number(item.classical_cv_seconds || 0),
    classicalCvDefectHint: item.classical_cv_defect_hint || null,
    hybridMode: item.hybrid_mode || 'off',
    hybridApplied: Boolean(item.hybrid_applied),
    hybridMapScore: item.hybrid_map_score == null ? null : Number(item.hybrid_map_score),
    yoloRoiState: item.yolo_roi_state || null,
    yoloRoiConfidence: item.yolo_roi_confidence == null ? null : Number(item.yolo_roi_confidence),
    yoloRoiClass: item.yolo_roi_class || null,
    mapAgreement: item.map_agreement == null ? null : Number(item.map_agreement),
    defectAreaPixels: Number(item.defect_area_pixels || 0),
    defectAreaFraction: Number(item.defect_area_fraction || 0),
    defectComponentCount: Number(item.defect_component_count || 0),
    defectBbox: item.defect_bbox_width ? {
        x: Number(item.defect_bbox_x || 0),
        y: Number(item.defect_bbox_y || 0),
        width: Number(item.defect_bbox_width || 0),
        height: Number(item.defect_bbox_height || 0),
    } : null,
    _assetPaths: {
        original: item.original_image_path || null,
        preprocessed: item.preprocessed_path || null,
        efficientad_heatmap: item.efficientad_heatmap_path || null,
        patchcore_heatmap: item.patchcore_heatmap_path || null,
        stage2_heatmap: item.stage2_heatmap_path || null,
        stage3_heatmap: item.stage3_heatmap_path || null,
        classical_cv_heatmap: item.classical_cv_heatmap_path || null,
        yolo_roi_mask: item.yolo_roi_mask_path || null,
        hybrid_heatmap: item.hybrid_heatmap_path || null,
        bbox_overlay: item.bbox_overlay_path || null,
        heatmap: item.heatmap_path || null,
        mask: item.mask_path || null,
        overlay: item.overlay_path || null,
    },
});

const downloadBlob = (blob, filename) => {
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = filename;
    document.body.appendChild(anchor);
    anchor.click();
    anchor.remove();
    window.setTimeout(() => URL.revokeObjectURL(url), 1500);
};

const revokeRecordAssets = (record) => {
    ['originalImage', 'preprocessedImage', 'efficientadHeatmapImage', 'patchcoreHeatmapImage', 'stage2HeatmapImage', 'stage3HeatmapImage', 'classicalCvHeatmapImage', 'yoloRoiMaskImage', 'hybridHeatmapImage', 'bboxOverlayImage', 'heatmapImage', 'maskImage', 'overlayImage'].forEach((key) => {
        const value = record?.[key];
        if (typeof value === 'string' && value.startsWith('blob:')) URL.revokeObjectURL(value);
    });
};

const mapJob = (item) => ({
    id: Number(item.job_id),
    callId: item.call_id,
    status: item.status || 'queued',
    category: item.category || 'unknown',
    datasetName: item.dataset_name || 'EVT-CLIP Inspection Profile',
    detectionId: item.detection_id || null,
    error: item.error || null,
    createdAt: item.created_at || null,
    updatedAt: item.updated_at || null,
});

const jobMessage = (status) => ({
    queued: 'Waiting for CPU worker',
    starting: 'Starting the inspection worker',
    running: 'Validating input and running EVT-CLIP inspection',
    complete: 'Finalizing result',
    failed: 'Inspection failed',
    timed_out: 'Inspection timed out',
    cancelled: 'Inspection cancelled',
}[status] || 'Preparing inspection');

export const DetectionProvider = ({ children }) => {
    const { user } = useContext(AuthContext);
    const [datasets, setDatasets] = useState(fallbackDatasets);
    const [history, setHistory] = useState([]);
    const [historyTotal, setHistoryTotal] = useState(0);
    const [loading, setLoading] = useState(false);
    const [jobStatus, setJobStatus] = useState('idle');
    const [jobs, setJobs] = useState([]);
    const [currentJob, setCurrentJob] = useState(null);

    const attachAssets = useCallback(async (item, originalOverride = '') => {
        const record = item._assetPaths ? item : mapDetection(item);
        const fetchAsset = async (name, exists) => {
            if (!exists) return '';
            try {
                const response = await api.get(`/detection/${record.id}/asset/${name}`, { responseType: 'blob' });
                return URL.createObjectURL(response.data);
            } catch {
                return '';
            }
        };
        const paths = record._assetPaths || {};
        const visualEvidenceAllowed = record.resultValid !== false;
        const [
            originalImage, preprocessedImage, efficientadHeatmapImage, patchcoreHeatmapImage,
            stage2HeatmapImage, stage3HeatmapImage, classicalCvHeatmapImage, yoloRoiMaskImage, hybridHeatmapImage, bboxOverlayImage, heatmapImage, maskImage, overlayImage,
        ] = await Promise.all([
            originalOverride || fetchAsset('original', paths.original),
            fetchAsset('preprocessed', visualEvidenceAllowed && paths.preprocessed),
            fetchAsset('efficientad_heatmap', visualEvidenceAllowed && paths.efficientad_heatmap),
            fetchAsset('patchcore_heatmap', visualEvidenceAllowed && paths.patchcore_heatmap),
            fetchAsset('stage2_heatmap', visualEvidenceAllowed && paths.stage2_heatmap),
            fetchAsset('stage3_heatmap', visualEvidenceAllowed && paths.stage3_heatmap),
            fetchAsset('classical_cv_heatmap', visualEvidenceAllowed && paths.classical_cv_heatmap),
            fetchAsset('yolo_roi_mask', visualEvidenceAllowed && paths.yolo_roi_mask),
            fetchAsset('hybrid_heatmap', visualEvidenceAllowed && paths.hybrid_heatmap),
            fetchAsset('bbox_overlay', visualEvidenceAllowed && paths.bbox_overlay),
            fetchAsset('heatmap', visualEvidenceAllowed && paths.heatmap),
            fetchAsset('mask', visualEvidenceAllowed && paths.mask),
            fetchAsset('overlay', visualEvidenceAllowed && paths.overlay),
        ]);
        return {
            ...record,
            originalImage: originalOverride || originalImage,
            preprocessedImage,
            efficientadHeatmapImage,
            patchcoreHeatmapImage,
            stage2HeatmapImage,
            stage3HeatmapImage,
            classicalCvHeatmapImage,
            yoloRoiMaskImage,
            hybridHeatmapImage,
            bboxOverlayImage,
            heatmapImage,
            maskImage,
            overlayImage,
        };
    }, []);

    const loadAssetsForDetection = useCallback(async (id) => {
        const existing = history.find((item) => String(item.id) === String(id));
        if (existing?.originalImage && (existing.resultValid === false || existing.heatmapImage || !existing._assetPaths?.heatmap)) return existing;
        const { data } = await api.get(`/detection/${id}`);
        const hydrated = await attachAssets(data);
        setHistory((items) => items.map((item) => String(item.id) === String(id) ? hydrated : item));
        return hydrated;
    }, [history, attachAssets]);

    const loadJobs = useCallback(async () => {
        if (!localStorage.getItem('visiontext_access_token')) { setJobs([]); return []; }
        try {
            const { data } = await api.get('/detect/jobs', { params: { limit: 25 } });
            const mapped = (data?.items || []).map(mapJob);
            setJobs(mapped);
            return mapped;
        } catch {
            return [];
        }
    }, []);

    const load = useCallback(async () => {
        if (!localStorage.getItem('visiontext_access_token')) return;
        const [detections, datasetResponse] = await Promise.all([
            api.get('/detections', { params: { limit: 100 } }),
            api.get('/datasets'),
        ]);
        // Keep list pages fast: metadata is enough. Visual evidence is fetched
        // only when a report is opened or a new inspection completes.
        setHistory((items) => {
            items.forEach(revokeRecordAssets);
            return detections.data.items.map(mapDetection);
        });
        setHistoryTotal(Number(detections.data.total || detections.data.items.length));
        setDatasets(datasetResponse.data.length
            ? datasetResponse.data.map((d) => ({
                ...d,
                id: String(d.id),
                categories: d.tags?.length ? d.tags : [d.category || 'metadata'],
                imagesCount: d.sample_count || 0,
                created: d.created_at?.slice(0, 10) || '—',
            }))
            : fallbackDatasets
        );
        await loadJobs();
    }, [loadJobs]);

    useEffect(() => {
        if (!user?.id || !localStorage.getItem('visiontext_access_token')) {
            setHistory((items) => { items.forEach(revokeRecordAssets); return []; });
            setHistoryTotal(0);
            setDatasets(fallbackDatasets);
            setJobs([]);
            setCurrentJob(null);
            return undefined;
        }
        load().catch(() => {
            setHistory((items) => { items.forEach(revokeRecordAssets); return []; });
            setHistoryTotal(0);
        });
        const timer = window.setInterval(() => { loadJobs(); }, 5000);
        return () => window.clearInterval(timer);
    }, [load, loadJobs, user?.id]);

    const loadOlderHistory = useCallback(async () => {
        if (history.length >= historyTotal) return [];
        const { data } = await api.get('/detections', { params: { skip: history.length, limit: 100 } });
        const mapped = data.items.map(mapDetection);
        setHistoryTotal(Number(data.total || historyTotal));
        setHistory((items) => {
            const known = new Set(items.map((item) => String(item.id)));
            return [...items, ...mapped.filter((item) => !known.has(String(item.id)))];
        });
        return mapped;
    }, [history.length, historyTotal]);

    const runDetection = async (imageFile, datasetId, category) => {
        setLoading(true);
        setJobStatus('Preparing image');
        setCurrentJob(null);
        let activeJobId = null;
        try {
            const form = new FormData();
            form.append('file', imageFile);
            const upload = await api.post('/upload', form, {
                headers: { 'Content-Type': 'multipart/form-data' },
                timeout: 30000,
            });

            setJobStatus('Submitting inspection');
            const selectedDataset = datasets.find((item) => String(item.id) === String(datasetId));
            const submission = await api.post('/detect/jobs', {
                image_path: upload.data.image_path,
                dataset_name: selectedDataset?.name || 'EVT-CLIP Inspection Profile',
                category,
            }, { timeout: 30000 });

            let job = submission.data;
            activeJobId = job.job_id;
            const startedAt = Date.now();
            setCurrentJob({ id: job.job_id, status: job.status, startedAt, category, callId: job.call_id, error: null });
            setJobStatus(jobMessage(job.status));
            await loadJobs();

            const MAX_CLIENT_TIMEOUT_MS = 120000;
            const POLL_INTERVAL_MS = 2000;
            const maxAttempts = Math.ceil(MAX_CLIENT_TIMEOUT_MS / POLL_INTERVAL_MS);

            for (let attempt = 0; attempt < maxAttempts; attempt += 1) {
                const elapsedMs = Date.now() - startedAt;
                if (elapsedMs > MAX_CLIENT_TIMEOUT_MS) {
                    break;
                }

                if (job.status === 'complete' && job.detection) {
                    // Move the UI to a terminal state before downloading optional visual evidence.
                    // Asset retrieval must not make a completed job look like it is checking again.
                    setCurrentJob((value) => value ? { ...value, status: 'complete', detectionId: job.detection.id } : value);
                    setJobStatus(job.detection.result_valid === false ? 'Input rejected' : 'Inspection complete');
                    const mapped = await attachAssets(job.detection, URL.createObjectURL(imageFile));
                    setHistory((items) => [mapped, ...items.filter((item) => String(item.id) !== String(mapped.id))]);
                    setHistoryTotal((total) => total + 1);
                    await loadJobs();
                    return mapped;
                }
                if (['failed', 'timed_out', 'cancelled'].includes(job.status)) {
                    const message = job.error || (job.status === 'timed_out' ? 'Inspection timed out.' : job.status === 'cancelled' ? 'Inspection was cancelled.' : 'CPU inference failed.');
                    setCurrentJob((value) => value ? { ...value, status: job.status, error: message } : value);
                    setJobStatus(jobMessage(job.status));
                    throw new Error(message);
                }

                setCurrentJob((value) => value ? { ...value, status: job.status, ageSeconds: Math.floor(elapsedMs / 1000) } : value);
                setJobStatus(jobMessage(job.status));
                await sleep(POLL_INTERVAL_MS);
                job = (await api.get(`/detect/jobs/${job.job_id}`, { timeout: 15000 })).data;
            }

            if (activeJobId) {
                try {
                    await api.post(`/detect/jobs/${activeJobId}/cancel`, null, { timeout: 10000 });
                } catch {
                    // best-effort cancellation
                }
            }
            setCurrentJob((value) => value ? { ...value, status: 'timed_out', error: 'Inspection took too long. Please retry.' } : value);
            setJobStatus('Inspection timed out');
            await loadJobs();
            throw new Error('Inspection took too long. Please retry.');
        } finally {
            setLoading(false);
        }
    };

    const cancelCurrentJob = async () => {
        if (!currentJob?.id || ['complete', 'failed', 'timed_out', 'cancelled'].includes(currentJob.status)) return;
        const { data } = await api.post(`/detect/jobs/${currentJob.id}/cancel`);
        setCurrentJob((value) => value ? { ...value, status: data.status, error: data.error || null } : value);
        setJobStatus(jobMessage(data.status));
        await loadJobs();
    };

    const retryJob = async (jobId) => {
        const { data } = await api.post(`/detect/jobs/${jobId}/retry`);
        await loadJobs();
        return data;
    };

    const generateAndDownloadReport = async (detectionId) => {
        const { data: report } = await api.post('/generate-report', {
            detection_id: detectionId,
            remarks: 'EVT-CLIP inspection report',
        });
        const response = await api.get(`/download-report/${report.id}`, { responseType: 'blob' });
        downloadBlob(response.data, `evt-clip-v2-report-${detectionId}.pdf`);
        return report;
    };

    const downloadEvidenceBundle = async (detectionId) => {
        const response = await api.get(`/export-evidence/${detectionId}`, {
            responseType: 'blob',
            timeout: 120000,
        });
        downloadBlob(response.data, `evt-clip-v2-evidence-${detectionId}.zip`);
    };

    const deleteReport = async (id) => {
        await api.delete(`/detection/${id}`);
        setHistory((items) => {
            const removed = items.find((item) => item.id === id);
            if (removed) revokeRecordAssets(removed);
            return items.filter((item) => String(item.id) !== String(id));
        });
        setHistoryTotal((total) => Math.max(0, total - 1));
    };

    const addDataset = async (dataset) => {
        const { data } = await api.post('/datasets', {
            name: dataset.name,
            description: dataset.description,
            category: dataset.category,
            tags: dataset.categories || [],
            sample_count: dataset.imagesCount || 0,
        });
        setDatasets((items) => [...items, {
            ...data,
            id: String(data.id),
            categories: data.tags?.length ? data.tags : [data.category],
            imagesCount: data.sample_count || 0,
            created: data.created_at?.slice(0, 10) || '—',
        }]);
    };

    const deleteDataset = async (id) => {
        await api.delete(`/datasets/${id}`);
        setDatasets((items) => items.filter((item) => String(item.id) !== String(id)));
    };

    return (
        <DetectionContext.Provider value={{
            datasets, history, historyTotal, loading, jobStatus, jobs, currentJob,
            apiUrl: API_BASE_URL, mlServerUrl: 'Modal CPU worker',
            runDetection, cancelCurrentJob, retryJob, addDataset, deleteDataset, deleteReport,
            generateAndDownloadReport, downloadEvidenceBundle,
            loadAssetsForDetection, loadOlderHistory, reload: load, reloadJobs: loadJobs,
        }}>
            {children}
        </DetectionContext.Provider>
    );
};
